#!/usr/bin/env python3
"""
gen_websettings.py <framework-classes.dex.jar> <amr-dir>

android.webkit.WebSettings is an abstract class, so java.lang.reflect.Proxy
cannot stand in for it -- which is why the adapter's inert WebView provider
hands back null from getSettings() and every WebView-backed screen dies with

    NPE: WebSettings.getUserAgentString() on null
    NPE: WebSettings.setGeolocationEnabled(boolean) on null

A concrete subclass fixes that once, for every caller.  All 104 abstract
methods are public, so a subclass outside the package is legal.

Rather than hand-write them, read the real class out of the platform's own dex
and emit both halves:

  <amr>/stubs/android/webkit/WebSettings.java   compile-only stand-in
  <amr>/src/westlake/webview/InertWebSettings.java   the shipped subclass

Re-run this whenever the platform's WebSettings changes.
"""
import subprocess, sys, os, re

HERE = os.path.dirname(os.path.abspath(__file__))

# Return values that matter to real callers; everything else gets a zero value.
SPECIAL_RETURNS = {
    'getUserAgentString':
        '"Mozilla/5.0 (Linux; Android 12; DAYU200) AppleWebKit/537.36 '
        '(KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36"',
    'getDefaultTextEncodingName': '"UTF-8"',
    'getStandardFontFamily': '"sans-serif"',
    'getFixedFontFamily': '"monospace"',
    'getSansSerifFontFamily': '"sans-serif"',
    'getSerifFontFamily': '"serif"',
    'getCursiveFontFamily': '"cursive"',
    'getFantasyFontFamily': '"fantasy"',
    'getDefaultFontSize': '16',
    'getDefaultFixedFontSize': '13',
    'getMinimumFontSize': '8',
    'getMinimumLogicalFontSize': '8',
    'getTextZoom': '100',
    'getLayoutAlgorithm': 'LayoutAlgorithm.NORMAL',
    'getPluginState': 'PluginState.OFF',
    'getDefaultZoom': 'ZoomDensity.MEDIUM',
}
ZERO = {'void': None, 'boolean': 'false', 'int': '0', 'long': '0L',
        'float': '0f', 'double': '0d', 'java.lang.String': '""'}

ENUMS = {  # nested enums the signatures reference, with the constants we use
    'LayoutAlgorithm': ['NORMAL', 'SINGLE_COLUMN', 'NARROW_COLUMNS', 'TEXT_AUTOSIZING'],
    'PluginState':     ['ON', 'ON_DEMAND', 'OFF'],
    'RenderPriority':  ['NORMAL', 'HIGH', 'LOW'],
    'ZoomDensity':     ['FAR', 'MEDIUM', 'CLOSE'],
    'TextSize':        ['SMALLEST', 'SMALLER', 'NORMAL', 'LARGER', 'LARGEST'],
}

def nested(t):
    m = re.match(r'android\.webkit\.WebSettings\$(\w+)$', t)
    return m.group(1) if m else None

def local(t):
    n = nested(t)
    return n if n else t

def main():
    fw, amr = sys.argv[1], sys.argv[2]
    out = subprocess.run(
        [sys.executable, os.path.join(HERE, 'dexabstract.py'),
         fw, 'Landroid/webkit/WebSettings;'],
        capture_output=True, text=True, check=True).stdout

    methods = []
    for line in out.splitlines():
        if not line.startswith('ABSTRACT'): continue
        _, flags, ret, sig = line.split('\t')
        name, args = sig.split('(', 1)
        args = args.rstrip(')')
        params = []
        if args.strip():
            for a in args.split(','):
                t, v = a.strip().rsplit(' ', 1)
                params.append((t, v))
        methods.append((ret, name, params))
    methods.sort(key=lambda m: (m[1], len(m[2])))

    enum_src = '\n'.join(
        f"    public enum {n} {{ {', '.join(c)} }}" for n, c in sorted(ENUMS.items()))

    # ---- compile-only stub ----
    lines = ["// GENERATED by patches/tools/gen_websettings.py -- do not edit.",
             "//",
             "// Compile-only stand-in for the platform's abstract",
             "// android.webkit.WebSettings.  Never shipped: d8 only takes the",
             "// classes under src/, these just satisfy javac.",
             "package android.webkit;", "",
             "public abstract class WebSettings {", enum_src, ""]
    for ret, name, params in methods:
        sig = ', '.join(f"{local(t)} {v}" for t, v in params)
        lines.append(f"    public abstract {local(ret)} {name}({sig});")
    lines += ["}", ""]
    stub = os.path.join(amr, 'stubs', 'android', 'webkit', 'WebSettings.java')
    os.makedirs(os.path.dirname(stub), exist_ok=True)
    open(stub, 'w').write('\n'.join(lines))

    # ---- shipped subclass ----
    lines = ["// GENERATED by patches/tools/gen_websettings.py -- do not edit.",
             "//",
             "// A concrete android.webkit.WebSettings.  The adapter has no real",
             "// WebView, so WebView.getSettings() returned null and every caller",
             "// that touched it died on the main thread:",
             "//",
             "//   NPE: WebSettings.getUserAgentString() on null",
             "//        at MediaAppUtil.getWebViewDefaultUserAgent",
             "//   NPE: WebSettings.setGeolocationEnabled(boolean) on null",
             "//        at BrowserFragment.onActivityCreated",
             "//",
             "// Proxy cannot help -- WebSettings is an abstract class, not an",
             "// interface.  So implement it: setters remember nothing, getters",
             "// answer with the platform defaults.  The point is only that no",
             "// caller ever sees null.",
             "package westlake.webview;", "",
             "import android.webkit.WebSettings;", "",
             "public final class InertWebSettings extends WebSettings {", ""]
    for ret, name, params in methods:
        sig = ', '.join(f"{local(t)} {v}" for t, v in params)
        body = ''
        if ret != 'void':
            v = SPECIAL_RETURNS.get(name)
            if v is None:
                n = nested(ret)
                v = f"{n}.{ENUMS[n][0]}" if n else ZERO.get(ret, 'null')
            body = f" return {v};"
        lines.append(f"    @Override public {local(ret)} {name}({sig}) {{{body} }}")
    lines += ["}", ""]
    sub = os.path.join(amr, 'src', 'westlake', 'webview', 'InertWebSettings.java')
    os.makedirs(os.path.dirname(sub), exist_ok=True)
    open(sub, 'w').write('\n'.join(lines))

    print(f"{len(methods)} abstract methods")
    print("stub    :", stub)
    print("subclass:", sub)

main()
