// GENERATED by patches/tools/gen_websettings.py -- do not edit.
//
// Compile-only stand-in for the platform's abstract
// android.webkit.WebSettings.  Never shipped: d8 only takes the
// classes under src/, these just satisfy javac.
package android.webkit;

public abstract class WebSettings {
    public enum LayoutAlgorithm { NORMAL, SINGLE_COLUMN, NARROW_COLUMNS, TEXT_AUTOSIZING }
    public enum PluginState { ON, ON_DEMAND, OFF }
    public enum RenderPriority { NORMAL, HIGH, LOW }
    public enum TextSize { SMALLEST, SMALLER, NORMAL, LARGER, LARGEST }
    public enum ZoomDensity { FAR, MEDIUM, CLOSE }

    public abstract boolean enableSmoothTransition();
    public abstract boolean getAcceptThirdPartyCookies();
    public abstract boolean getAllowContentAccess();
    public abstract boolean getAllowFileAccess();
    public abstract boolean getAllowFileAccessFromFileURLs();
    public abstract boolean getAllowUniversalAccessFromFileURLs();
    public abstract boolean getBlockNetworkImage();
    public abstract boolean getBlockNetworkLoads();
    public abstract boolean getBuiltInZoomControls();
    public abstract int getCacheMode();
    public abstract java.lang.String getCursiveFontFamily();
    public abstract boolean getDatabaseEnabled();
    public abstract java.lang.String getDatabasePath();
    public abstract int getDefaultFixedFontSize();
    public abstract int getDefaultFontSize();
    public abstract java.lang.String getDefaultTextEncodingName();
    public abstract ZoomDensity getDefaultZoom();
    public abstract int getDisabledActionModeMenuItems();
    public abstract boolean getDisplayZoomControls();
    public abstract boolean getDomStorageEnabled();
    public abstract java.lang.String getFantasyFontFamily();
    public abstract java.lang.String getFixedFontFamily();
    public abstract boolean getJavaScriptCanOpenWindowsAutomatically();
    public abstract boolean getJavaScriptEnabled();
    public abstract LayoutAlgorithm getLayoutAlgorithm();
    public abstract boolean getLightTouchEnabled();
    public abstract boolean getLoadWithOverviewMode();
    public abstract boolean getLoadsImagesAutomatically();
    public abstract boolean getMediaPlaybackRequiresUserGesture();
    public abstract int getMinimumFontSize();
    public abstract int getMinimumLogicalFontSize();
    public abstract int getMixedContentMode();
    public abstract boolean getNavDump();
    public abstract boolean getOffscreenPreRaster();
    public abstract PluginState getPluginState();
    public abstract boolean getPluginsEnabled();
    public abstract boolean getSafeBrowsingEnabled();
    public abstract java.lang.String getSansSerifFontFamily();
    public abstract boolean getSaveFormData();
    public abstract boolean getSavePassword();
    public abstract java.lang.String getSerifFontFamily();
    public abstract java.lang.String getStandardFontFamily();
    public abstract int getTextZoom();
    public abstract boolean getUseWebViewBackgroundForOverscrollBackground();
    public abstract boolean getUseWideViewPort();
    public abstract int getUserAgent();
    public abstract java.lang.String getUserAgentString();
    public abstract boolean getVideoOverlayForEmbeddedEncryptedVideoEnabled();
    public abstract void setAcceptThirdPartyCookies(boolean a0);
    public abstract void setAllowContentAccess(boolean a0);
    public abstract void setAllowFileAccess(boolean a0);
    public abstract void setAllowFileAccessFromFileURLs(boolean a0);
    public abstract void setAllowUniversalAccessFromFileURLs(boolean a0);
    public abstract void setBlockNetworkImage(boolean a0);
    public abstract void setBlockNetworkLoads(boolean a0);
    public abstract void setBuiltInZoomControls(boolean a0);
    public abstract void setCacheMode(int a0);
    public abstract void setCursiveFontFamily(java.lang.String a0);
    public abstract void setDatabaseEnabled(boolean a0);
    public abstract void setDatabasePath(java.lang.String a0);
    public abstract void setDefaultFixedFontSize(int a0);
    public abstract void setDefaultFontSize(int a0);
    public abstract void setDefaultTextEncodingName(java.lang.String a0);
    public abstract void setDefaultZoom(ZoomDensity a0);
    public abstract void setDisabledActionModeMenuItems(int a0);
    public abstract void setDisplayZoomControls(boolean a0);
    public abstract void setDomStorageEnabled(boolean a0);
    public abstract void setEnableSmoothTransition(boolean a0);
    public abstract void setFantasyFontFamily(java.lang.String a0);
    public abstract void setFixedFontFamily(java.lang.String a0);
    public abstract void setGeolocationDatabasePath(java.lang.String a0);
    public abstract void setGeolocationEnabled(boolean a0);
    public abstract void setJavaScriptCanOpenWindowsAutomatically(boolean a0);
    public abstract void setJavaScriptEnabled(boolean a0);
    public abstract void setLayoutAlgorithm(LayoutAlgorithm a0);
    public abstract void setLightTouchEnabled(boolean a0);
    public abstract void setLoadWithOverviewMode(boolean a0);
    public abstract void setLoadsImagesAutomatically(boolean a0);
    public abstract void setMediaPlaybackRequiresUserGesture(boolean a0);
    public abstract void setMinimumFontSize(int a0);
    public abstract void setMinimumLogicalFontSize(int a0);
    public abstract void setMixedContentMode(int a0);
    public abstract void setNavDump(boolean a0);
    public abstract void setNeedInitialFocus(boolean a0);
    public abstract void setOffscreenPreRaster(boolean a0);
    public abstract void setPluginState(PluginState a0);
    public abstract void setPluginsEnabled(boolean a0);
    public abstract void setRenderPriority(RenderPriority a0);
    public abstract void setSafeBrowsingEnabled(boolean a0);
    public abstract void setSansSerifFontFamily(java.lang.String a0);
    public abstract void setSaveFormData(boolean a0);
    public abstract void setSavePassword(boolean a0);
    public abstract void setSerifFontFamily(java.lang.String a0);
    public abstract void setStandardFontFamily(java.lang.String a0);
    public abstract void setSupportMultipleWindows(boolean a0);
    public abstract void setSupportZoom(boolean a0);
    public abstract void setTextZoom(int a0);
    public abstract void setUseWebViewBackgroundForOverscrollBackground(boolean a0);
    public abstract void setUseWideViewPort(boolean a0);
    public abstract void setUserAgent(int a0);
    public abstract void setUserAgentString(java.lang.String a0);
    public abstract void setVideoOverlayForEmbeddedEncryptedVideoEnabled(boolean a0);
    public abstract boolean supportMultipleWindows();
    public abstract boolean supportZoom();
}
