com.tencent.mm.BuildInfo.CLIENT_VERSION=0x28004d30
com.tencent.mm.BuildInfo.OPEN_SDK_VERSION=671108400
com.tencent.mm.BuildInfo.OPEN_SDK_SUPPORT_WMPF_REDIRECTING_PAGE=true
com.tencent.mm.BuildInfo.BUILD_IS_ARM64=true
com.hihonor.mcs.client.appid=104419772
com.tencent.mm.BuildInfo.BUILD_TAG=Android_Wechat_RELEASE_WUKONG #7639
com.tencent.mm.BuildInfo.BUILD_TIME=2026-08-22 17:22:16
com.tencent.mm.BuildInfo.BUILD_COMMAND=null
com.tencent.mm.BuildInfo.BUILD_REV=14d41864c67588e539c7b8982e3513d0708bf392
com.tencent.mm.BuildInfo.BUILD_SVNPATH=dev/2026-t7/special_0822@git
com.tencent.mm.BuildInfo.PATCH_ENABLED=true
com.tencent.mm.BuildInfo.BUILD_AAB_FLAG=null
sensorCompatTreatmentEnable=true
com.sec.android.support.multiwindow=true
com.sec.android.multiwindow.DEFAULT_SIZE_W=632.0dip
com.sec.android.multiwindow.DEFAULT_SIZE_H=598.0dip
com.sec.android.multiwindow.MINIMUM_SIZE_W=632.0dip
com.sec.android.multiwindow.MINIMUM_SIZE_H=598.0dip
honor.splashscreen.type=1
android.max_aspect=0x4019999a(t=0x4)
android.vendor.full_screen=true
android.vivo_multidisplay_support=true
VivoMultiSupport=true
android.notch_support=true
android.allow_multiple_resumed_activities=true
embedded=true
android.vivo_nightmode_support=false
com.coloros.DisableSystemDarkMode=true
wx_qlauncher_coop=fun1,fun2
wechat_fun_support=ext1
wechat_ext_api_level=12
SupportedAirMsgVersion=1.0.0
SupportedSharedFileVideoVersion=1.0.0
EasyGoClient=true
com.tencent.mm.BuildInfo.OPEN_SDK_PAY_ENTRY_CLASSNAME=com.tencent.mm.plugin.base.stub.WXPayEntryActivity
support_minors_mode=1
com.tencent.mm.ui.SplitWindowInitializer=androidx.startup
androidx.profileinstaller.ProfileInstallerInitializer=androidx.startup
TencentGeoLocationSDK=wechat,JJBLX-KSS3T-AYHOO-5G2NV-KRPVU
google_analytics_adid_collection_enabled=false
firebase_messaging_auto_init_enabled=false
firebase_analytics_collection_enabled=false
TencentMapSDK=00e3d061e7debe5f88aec44e0b549b76
miuiWidgetVersion=1
miuiWidget=true
org.chromium.content.browser.NUM_SANDBOXED_SERVICES=1
org.chromium.content.browser.NUM_PRIVILEGED_SERVICES=1
androidx.camera.core.impl.MetadataHolderService.DEFAULT_CONFIG_PROVIDER=androidx.camera.camera2.Camera2Config$DefaultProvider
tinker_version=1.9.15.3
buildType=release
com.google.firebase.components:com.google.firebase.iid.Registrar=com.google.firebase.components.ComponentRegistrar
com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar=com.google.firebase.components.ComponentRegistrar
TMS_ShellConfig=com.tencent.mapsdk.BuildConfig
TINKER_ID=tinker_id_14d41864c67588e539c7b8982e3513d0708bf392_arm64-v8a
