// GENERATED by patches/tools/gen_websettings.py -- do not edit.
//
// A concrete android.webkit.WebSettings.  The adapter has no real
// WebView, so WebView.getSettings() returned null and every caller
// that touched it died on the main thread:
//
//   NPE: WebSettings.getUserAgentString() on null
//        at MediaAppUtil.getWebViewDefaultUserAgent
//   NPE: WebSettings.setGeolocationEnabled(boolean) on null
//        at BrowserFragment.onActivityCreated
//
// Proxy cannot help -- WebSettings is an abstract class, not an
// interface.  So implement it: setters remember nothing, getters
// answer with the platform defaults.  The point is only that no
// caller ever sees null.
package westlake.webview;

import android.webkit.WebSettings;

public final class InertWebSettings extends WebSettings {

    @Override public boolean enableSmoothTransition() { return false; }
    @Override public boolean getAcceptThirdPartyCookies() { return false; }
    @Override public boolean getAllowContentAccess() { return false; }
    @Override public boolean getAllowFileAccess() { return false; }
    @Override public boolean getAllowFileAccessFromFileURLs() { return false; }
    @Override public boolean getAllowUniversalAccessFromFileURLs() { return false; }
    @Override public boolean getBlockNetworkImage() { return false; }
    @Override public boolean getBlockNetworkLoads() { return false; }
    @Override public boolean getBuiltInZoomControls() { return false; }
    @Override public int getCacheMode() { return 0; }
    @Override public java.lang.String getCursiveFontFamily() { return "cursive"; }
    @Override public boolean getDatabaseEnabled() { return false; }
    @Override public java.lang.String getDatabasePath() { return ""; }
    @Override public int getDefaultFixedFontSize() { return 13; }
    @Override public int getDefaultFontSize() { return 16; }
    @Override public java.lang.String getDefaultTextEncodingName() { return "UTF-8"; }
    @Override public ZoomDensity getDefaultZoom() { return ZoomDensity.MEDIUM; }
    @Override public int getDisabledActionModeMenuItems() { return 0; }
    @Override public boolean getDisplayZoomControls() { return false; }
    @Override public boolean getDomStorageEnabled() { return false; }
    @Override public java.lang.String getFantasyFontFamily() { return "fantasy"; }
    @Override public java.lang.String getFixedFontFamily() { return "monospace"; }
    @Override public boolean getJavaScriptCanOpenWindowsAutomatically() { return false; }
    @Override public boolean getJavaScriptEnabled() { return false; }
    @Override public LayoutAlgorithm getLayoutAlgorithm() { return LayoutAlgorithm.NORMAL; }
    @Override public boolean getLightTouchEnabled() { return false; }
    @Override public boolean getLoadWithOverviewMode() { return false; }
    @Override public boolean getLoadsImagesAutomatically() { return false; }
    @Override public boolean getMediaPlaybackRequiresUserGesture() { return false; }
    @Override public int getMinimumFontSize() { return 8; }
    @Override public int getMinimumLogicalFontSize() { return 8; }
    @Override public int getMixedContentMode() { return 0; }
    @Override public boolean getNavDump() { return false; }
    @Override public boolean getOffscreenPreRaster() { return false; }
    @Override public PluginState getPluginState() { return PluginState.OFF; }
    @Override public boolean getPluginsEnabled() { return false; }
    @Override public boolean getSafeBrowsingEnabled() { return false; }
    @Override public java.lang.String getSansSerifFontFamily() { return "sans-serif"; }
    @Override public boolean getSaveFormData() { return false; }
    @Override public boolean getSavePassword() { return false; }
    @Override public java.lang.String getSerifFontFamily() { return "serif"; }
    @Override public java.lang.String getStandardFontFamily() { return "sans-serif"; }
    @Override public int getTextZoom() { return 100; }
    @Override public boolean getUseWebViewBackgroundForOverscrollBackground() { return false; }
    @Override public boolean getUseWideViewPort() { return false; }
    @Override public int getUserAgent() { return 0; }
    @Override public java.lang.String getUserAgentString() { return "Mozilla/5.0 (Linux; Android 12; DAYU200) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36"; }
    @Override public boolean getVideoOverlayForEmbeddedEncryptedVideoEnabled() { return false; }
    @Override public void setAcceptThirdPartyCookies(boolean a0) { }
    @Override public void setAllowContentAccess(boolean a0) { }
    @Override public void setAllowFileAccess(boolean a0) { }
    @Override public void setAllowFileAccessFromFileURLs(boolean a0) { }
    @Override public void setAllowUniversalAccessFromFileURLs(boolean a0) { }
    @Override public void setBlockNetworkImage(boolean a0) { }
    @Override public void setBlockNetworkLoads(boolean a0) { }
    @Override public void setBuiltInZoomControls(boolean a0) { }
    @Override public void setCacheMode(int a0) { }
    @Override public void setCursiveFontFamily(java.lang.String a0) { }
    @Override public void setDatabaseEnabled(boolean a0) { }
    @Override public void setDatabasePath(java.lang.String a0) { }
    @Override public void setDefaultFixedFontSize(int a0) { }
    @Override public void setDefaultFontSize(int a0) { }
    @Override public void setDefaultTextEncodingName(java.lang.String a0) { }
    @Override public void setDefaultZoom(ZoomDensity a0) { }
    @Override public void setDisabledActionModeMenuItems(int a0) { }
    @Override public void setDisplayZoomControls(boolean a0) { }
    @Override public void setDomStorageEnabled(boolean a0) { }
    @Override public void setEnableSmoothTransition(boolean a0) { }
    @Override public void setFantasyFontFamily(java.lang.String a0) { }
    @Override public void setFixedFontFamily(java.lang.String a0) { }
    @Override public void setGeolocationDatabasePath(java.lang.String a0) { }
    @Override public void setGeolocationEnabled(boolean a0) { }
    @Override public void setJavaScriptCanOpenWindowsAutomatically(boolean a0) { }
    @Override public void setJavaScriptEnabled(boolean a0) { }
    @Override public void setLayoutAlgorithm(LayoutAlgorithm a0) { }
    @Override public void setLightTouchEnabled(boolean a0) { }
    @Override public void setLoadWithOverviewMode(boolean a0) { }
    @Override public void setLoadsImagesAutomatically(boolean a0) { }
    @Override public void setMediaPlaybackRequiresUserGesture(boolean a0) { }
    @Override public void setMinimumFontSize(int a0) { }
    @Override public void setMinimumLogicalFontSize(int a0) { }
    @Override public void setMixedContentMode(int a0) { }
    @Override public void setNavDump(boolean a0) { }
    @Override public void setNeedInitialFocus(boolean a0) { }
    @Override public void setOffscreenPreRaster(boolean a0) { }
    @Override public void setPluginState(PluginState a0) { }
    @Override public void setPluginsEnabled(boolean a0) { }
    @Override public void setRenderPriority(RenderPriority a0) { }
    @Override public void setSafeBrowsingEnabled(boolean a0) { }
    @Override public void setSansSerifFontFamily(java.lang.String a0) { }
    @Override public void setSaveFormData(boolean a0) { }
    @Override public void setSavePassword(boolean a0) { }
    @Override public void setSerifFontFamily(java.lang.String a0) { }
    @Override public void setStandardFontFamily(java.lang.String a0) { }
    @Override public void setSupportMultipleWindows(boolean a0) { }
    @Override public void setSupportZoom(boolean a0) { }
    @Override public void setTextZoom(int a0) { }
    @Override public void setUseWebViewBackgroundForOverscrollBackground(boolean a0) { }
    @Override public void setUseWideViewPort(boolean a0) { }
    @Override public void setUserAgent(int a0) { }
    @Override public void setUserAgentString(java.lang.String a0) { }
    @Override public void setVideoOverlayForEmbeddedEncryptedVideoEnabled(boolean a0) { }
    @Override public boolean supportMultipleWindows() { return false; }
    @Override public boolean supportZoom() { return false; }
}
